export default class RoutersConst {
  static readonly MAIN_PAGE_URL: string = 'pages/MainPage/Index';
  static readonly MAIN_PAGE_TAG: string = '[MainPage]';

  static readonly MINE_ACCOMPANIMENT_URL: string = 'pages/Mine/Accompaniment';
  static readonly MINE_ACCOMPANIMENT_TAG: string = '[MineAccompaniment]';

  static readonly MINE_LOCAL_RECORD_URL: string = 'pages/Mine/LocalRecord';
  static readonly MINE_LOCAL_RECORD_TAG: string = '[MineLocalRecord]';

  static readonly MINE_KCOIN_ACCOUNT_URL: string = 'pages/Mine/KCoinAccount';
  static readonly MINE_KCOIN_ACCOUNT_TAG: string = '[MineKCoinAccount]';

  static readonly MINE_SONG_COLLECTION_URL: string = 'pages/Mine/SongCollection';
  static readonly MINE_SONG_COLLECTION_TAG: string = '[MineSongCollection]';
}

