export default class RoutersConst {
  static readonly MAIN_PAGE_URL: string = 'pages/MainPage/Index';
  static readonly MAIN_PAGE_TAG: string = '[MainPage]';

  static readonly MINE_ACCOMPANIMENT_URL: string = 'pages/Mine/Accompaniment';
  static readonly MINE_ACCOMPANIMENT_TAG: string = '[MineAccompaniment]';

  static readonly MINE_LOCAL_RECORD_URL: string = 'pages/Mine/LocalRecord';
  static readonly MINE_LOCAL_RECORD_TAG: string = '[MineLocalRecord]';

  static readonly MINE_KCOIN_ACCOUNT_URL: string = 'pages/Mine/KCoinAccount';
  static readonly MINE_KCOIN_ACCOUNT_TAG: string = '[MineKCoinAccount]';

  static readonly MINE_SONG_COLLECTION_URL: string = 'pages/Mine/SongCollection';
  static readonly MINE_SONG_COLLECTION_TAG: string = '[MineSongCollection]';

  static readonly MESSAGE_RECEIVE_GIFTS_URL: string = 'pages/Message/ReceiveGifts';
  static readonly MESSAGE_RECEIVE_GIFTS_TAG: string = '[MessageReceiveGifts]';

  static readonly MESSAGE_RECENT_AUDIENCE_URL: string = 'pages/Message/RecentAudience';
  static readonly MESSAGE_RECENT_AUDIENCE_TAG: string = '[MessageRecentAudience]';

  static readonly MESSAGE_PRIVATE_URL: string = 'pages/Message/PrivateMessage';
  static readonly MESSAGE_PRIVATE_TAG: string = '[MessagePrivateMessage]';

  static readonly DISCOVERY_SEARCH_USER_URL: string = 'pages/Discovery/SearchUser';
  static readonly DISCOVERY_SEARCH_USER_TAG: string = '[DiscoverySearchUser]';

  static readonly DISCOVERY_CONTEST_URL: string = 'pages/Discovery/Contest';
  static readonly DISCOVERY_CONTEST_TAG: string = '[DiscoveryContest]';

  static readonly DISCOVERY_HOT_LIST_URL: string = 'pages/Discovery/HotList';
  static readonly DISCOVERY_HOT_LIST_TAG: string = '[DiscoveryHotList]';

  static readonly DISCOVERY_HOT_LIST_DETAIL_URL: string = 'pages/Discovery/HotListDetail';
  static readonly DISCOVERY_HOT_LIST_DETAIL_TAG: string = '[DiscoveryHotListDetail]';
}
