@Entry
@Component
struct HotListDetail {
  @State songList: Array<any> = [
    {
      "rank": 1,
      "rankType": 3,
      "rankValue": "0",
      "recType": 0,
      "songId": 247347346,
      "vid": "",
      "albumMid": "0049MVh824D7bM",
      "title": "句号",
      "singerName": "G.E.M. 邓紫棋",
      "singerMid": "001fNHEf1SFEFN",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "http://y.gtimg.cn/music/photo_new/T002R300x300M0000049MVh824D7bM_1.jpg",
      "mvId": 1,
      "payPlay": 1,
      "songTag": "一个好友关注歌手"
    }, {
      "rank": 2,
      "rankType": 3,
      "rankValue": "0",
      "recType": 0,
      "songId": 457240977,
      "vid": "",
      "albumMid": "001ln9YB420a7b",
      "title": "圣诞星 (feat. 杨瑞代)",
      "singerName": "周杰伦",
      "singerMid": "0025NhlN2yWrP4",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "http://y.gtimg.cn/music/photo_new/T002R300x300M000001ln9YB420a7b_1.jpg",
      "mvId": 1,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 3,
      "rankType": 1,
      "rankValue": "1",
      "recType": 0,
      "songId": 445588102,
      "vid": "",
      "albumMid": "001ROjU44eoKxM",
      "title": "西楼儿女",
      "singerName": "岳云鹏",
      "singerMid": "0003CDDY4bDRAj",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "http://y.gtimg.cn/music/photo_new/T002R300x300M000001ROjU44eoKxM_1.jpg",
      "mvId": 0,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 4,
      "rankType": 1,
      "rankValue": "1",
      "recType": 0,
      "songId": 473137,
      "vid": "",
      "albumMid": "003ha6C92GRuVE",
      "title": "偏爱",
      "singerName": "张芸京",
      "singerMid": "000acPsp0cfUZr",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": "听的人很心酸"
    }, {
      "rank": 5,
      "rankType": 1,
      "rankValue": "1",
      "recType": 0,
      "songId": 460432459,
      "vid": "",
      "albumMid": "000xyAMz2BqIb7",
      "title": "离别开出花 (弹唱版)",
      "singerName": "就是南方凯",
      "singerMid": "002zPxu14crYMp",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 0,
      "payPlay": 0,
    "songTag": ""
    }, {
      "rank": 6,
      "rankType": 1,
      "rankValue": "4",
      "recType": 0,
      "songId": 273032704,
      "vid": "",
      "albumMid": "000pVkCf3KsUQ9",
      "title": "天下",
      "singerName": "张杰",
      "singerMid": "002azErJ0UcDN6",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 7,
      "rankType": 3,
      "rankValue": "0",
      "recType": 0,
      "songId": 1030353,
      "vid": "",
      "albumMid": "001aC9dM35U6KB",
      "title": "Letting Go",
      "singerName": "蔡健雅",
      "singerMid": "000hNnWC3kko2c",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": "2个好友收藏"
    }, {
      "rank": 8,
      "rankType": 2,
      "rankValue": "5",
      "recType": 0,
      "songId": 458469266,
      "vid": "",
      "albumMid": "004fvS6O2mle0u",
      "title": "藏在你的名字里",
      "singerName": "单依纯",
      "singerMid": "002ug9Ha2zYM1y",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 0,
    "songTag": ""
    }, {
      "rank": 9,
      "rankType": 1,
      "rankValue": "8",
      "recType": 0,
      "songId": 394086810,
      "vid": "",
      "albumMid": "004ah8YC0dkfbz",
      "title": "我会等",
      "singerName": "承桓",
      "singerMid": "002RHvPq0fwAml",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 0,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 10,
      "rankType": 2,
      "rankValue": "2",
      "recType": 0,
      "songId": 624649,
      "vid": "",
      "albumMid": "002dOge41xlS8x",
      "title": "红色高跟鞋",
      "singerName": "蔡健雅",
      "singerMid": "000hNnWC3kko2c",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 11,
      "rankType": 1,
      "rankValue": "2",
      "recType": 0,
      "songId": 380221029,
      "vid": "",
      "albumMid": "000Nru2B0KDWty",
      "title": "西楼儿女",
      "singerName": "海来阿木",
      "singerMid": "004WYT5j1s7R6Y",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": "银河计划"
    }, {
      "rank": 12,
      "rankType": 3,
      "rankValue": "0",
      "recType": 0,
      "songId": 102174489,
      "vid": "",
      "albumMid": "003c616O2Zlswm",
      "title": "多远都要在一起",
      "singerName": "G.E.M. 邓紫棋",
      "singerMid": "001fNHEf1SFEFN",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 13,
      "rankType": 1,
      "rankValue": "2",
      "recType": 0,
      "songId": 326584182,
      "vid": "",
      "albumMid": "004Kbn3m2HV9Y3",
      "title": "如愿",
      "singerName": "王菲",
      "singerMid": "000GDDuQ3sGQiT",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 14,
      "rankType": 2,
      "rankValue": "3",
      "recType": 0,
      "songId": 422061155,
      "vid": "",
      "albumMid": "001qvyI10urb5z",
      "title": "瞬",
      "singerName": "郑润泽",
      "singerMid": "004AapHP4JP1Z2",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 0,
      "payPlay": 1,
    "songTag": "流行top100"
    }, {
      "rank": 15,
      "rankType": 1,
      "rankValue": "1",
      "recType": 0,
      "songId": 371325414,
      "vid": "",
      "albumMid": "002F6h4l0BU7vy",
      "title": "迟来的爱 (新版)",
      "singerName": "金润吉",
      "singerMid": "002gC7Yc0KoAJ2",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 0,
      "payPlay": 1,
    "songTag": "银河计划"
    }, {
      "rank": 16,
      "rankType": 1,
      "rankValue": "154",
      "recType": 0,
      "songId": 12628,
      "vid": "",
      "albumMid": "003jh8m13nL4IH",
      "title": "偷心",
      "singerName": "张学友",
      "singerMid": "004Be55m1SJaLk",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 0,
    "songTag": ""
    }, {
      "rank": 17,
      "rankType": 1,
      "rankValue": "1",
      "recType": 0,
      "songId": 770724,
      "vid": "",
      "albumMid": "00458UNF0evQeN",
      "title": "如果这就是爱情",
      "singerName": "张靓颖",
      "singerMid": "000aw4WC2EQYTv",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 18,
      "rankType": 1,
      "rankValue": "2",
      "recType": 0,
      "songId": 294095266,
      "vid": "",
      "albumMid": "001MyK3Y47zLur",
      "title": "一路生花",
      "singerName": "温奕心",
      "singerMid": "003k64X11As4qX",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": "开局就不同凡响啊"
    }, {
      "rank": 19,
      "rankType": 2,
      "rankValue": "5",
      "recType": 0,
      "songId": 420567049,
      "vid": "",
      "albumMid": "000volzn0tBZrp",
      "title": "想你时风起",
      "singerName": "单依纯",
      "singerMid": "002ug9Ha2zYM1y",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 0,
      "payPlay": 1,
    "songTag": ""
    }, {
      "rank": 20,
      "rankType": 1,
      "rankValue": "4",
      "recType": 0,
      "songId": 102350740,
      "vid": "",
      "albumMid": "003vyvvf2kbfel",
      "title": "此生不换",
      "singerName": "青鸟飞鱼",
      "singerMid": "0032tJkm2MGj8i",
      "songType": 0,
      "uuidCnt": 0,
      "cover": "",
      "mvId": 1,
      "payPlay": 1,
    "songTag": "十大中文金曲获奖"
    }
  ]

  @Builder songItem(song: any) {
    Row() {
      Column() {
        if (song.rank < 4) {
          Text(`${song.rank}`).fontColor('#E7645F').fontWeight(FontWeight.Bold).fontSize('24fp')
        } else {
          Text(`${song.rank}`).fontColor('#484949').fontWeight(FontWeight.Bold).fontSize('16fp')
        }

        if (song.rankType === 1) {
          Row() {
            // 画三角
            Polygon({ width: 8, height: 8 })
              .points([[0, 8], [4, 0], [8, 8]])
              .fill('#E7645F')

            Text(song.rankValue).margin({left: '6vp'}).fontColor('#E6645F').fontSize('10fp')
          }
          .margin({top: '4vp'})
        }

        if (song.rankType === 2) {
          Row() {
            // 画三角
            Polygon({ width: 8, height: 8 })
              .points([[0, 0], [4, 8], [8, 0]])
              .fill('#6482E6')

            Text(song.rankValue).margin({left: '6vp'}).fontColor('#6482E6').fontSize('10fp')
          }
          .margin({top: '4vp'})
        }

        if (song.rankType === 3) {
          Divider().width('8vp').strokeWidth('4vp').color('#828484')
        }

      }
      .justifyContent(FlexAlign.Center)
      .height('46vp')
      .width('28vp')
      .margin({right: '8vp'})

      if (song.cover) {
        Image(song.cover)
          .width('40vp')
          .margin({right: '8vp'})
          .borderRadius('4vp')
      }

      Column() {
        Row() {
          Text(song.title).fontSize('14fp').fontColor('#222222').margin({right: '4vp'})

          if (song.songTag) {
            Text(song.songTag)
              .padding({top: '2vp', right: '5vp', bottom: '2vp', left: '5vp'})
              .fontSize('10fp')
              .fontColor('#79E29B')
              .borderRadius('4vp')
              .backgroundColor('#E0F1EB')
          }
        }
        .margin({bottom: '8vp'})

        Row() {
          if (song.payPlay) {
            Text('VIP')
            .padding({top: '1vp', right: '3vp', bottom: '1vp', left: '3vp'})
            .margin({right: '4vp'})
            .fontSize('10fp')
            .fontColor('#79E29B')
            .fontWeight(FontWeight.Bold)
            .border({
              color: '#79E29B',
              width: '1vp',
              radius: '3vp'
            })
          }
          if (song.mvId) {
            Text('臻品母带')
              .padding({top: '1vp', right: '3vp', bottom: '1vp', left: '3vp'})
              .margin({right: '4vp'})
              .fontSize('10fp')
              .fontColor('#DDB25C')
              .fontWeight(FontWeight.Bold)
              .border({
                color: '#DDB25C',
                width: '1vp',
                radius: '3vp'
              })
          }

          Text(`${song.singerName} · ${song.title}`.split('').join('\u200B'))
            .layoutWeight(1)
            .fontSize('12fp')
            .fontColor('#999999')
            .textOverflow({ overflow: TextOverflow.Ellipsis })
            .maxLines(1)
        }

      }
      .alignItems(HorizontalAlign.Start)
      .layoutWeight(1)

      Image($r('app.media.discovery_like')).width('15vp').height('15vp')
      Image($r('app.media.discovery_add_music')).width('15vp').height('15vp').margin({left: '6vp'})
      Image($r('app.media.discovery_more')).width('15vp').height('15vp').margin({left: '2vp'})

    }
    .width('100%')
    // .height('54vp')
    .padding({left: '10vp', right: '10vp', bottom: '10vp'})
  }

  build() {
    Column() {
      Scroll() {
        Column() {
          Stack({alignContent: Alignment.Bottom}) {
            Image($r('app.media.ghy_singer_2'))
              .width('100%')
              .height('240vp')

            Row()
              .width('100%')
              .height('240vp')
              .linearGradient({
                direction: GradientDirection.Bottom, // 渐变方向
                colors: [
                  ['rgba(255, 255, 255, 0)', 0],
                  // ['rgba(255, 255, 255, 0.2)', 0.2],
                  // ['rgba(255, 255, 255, 0.3)', 0.3],
                  // ['rgba(255, 255, 255, 0.4)', 0.4],
                  ['rgba(255, 255, 255, 0.1)', 0.6],
                  ['rgba(255, 255, 255, 0.3)', 0.7],
                  ['rgba(255, 255, 255, 0.8)', 0.95],
                  ['rgba(255, 255, 255, 1)', 1],
                ]
              })
              // .shadow({ radius: 20, color: 'rgba(255, 255, 255, 0.1)', offsetY: 20 })


            Text('一口气全听完！每首都是宝藏歌曲')
              .width('100%')
              .padding({right: '20vp', bottom: '10vp', left: '20vp'})
              .fontWeight(FontWeight.Bold)
              .fontSize('20fp')
              .fontColor('#222222')

            Row() {
              Text('本歌单都是小编精挑细选的好歌曲，每一首都跟耐听，不信你听听，保准你听了不后悔，直呼很好听，一口气全部听完。'.split('').join('\u200B'))
                .layoutWeight(1)
                .height('18vp')
                .fontSize('12fp')
                .fontColor('#999999')
                .textOverflow({ overflow: TextOverflow.Ellipsis })
                .maxLines(1)

              Image($r('app.media.mine_right')).width('17vp').height('17vp')
            }
            .padding({left: '20vp', right: '20vp'})
            .translate({y: '16vp'})
          }
          .margin({bottom: '20vp'})

          Row() {
            Image($r('app.media.ghy_singer_8')).width('26vp').height('26vp').borderRadius(50)
            Text('周杰伦').fontSize('10fp').fontColor('#222222').margin({left: '10vp', right: '10vp'})
            Image($r('app.media.discovery_headset')).width('10vp').height('10vp').margin({right: '4vp'})
            Text('2258.1 万').fontSize('10fp').fontColor('#222222').fontWeight(FontWeight.Bold)
          }
          .width('100%')
          .height('48vp')
          .padding({left: '10vp', right: '10vp'})

          Row() {
            Row() {
              Image($r('app.media.discovery_play')).width('30vp').height('30vp')
              Text('全部播放(130)').fontSize('14fp').fontColor('#222222').margin({left: '10vp', right: '10vp'})
            }

            Row() {
              Text('去QQ音乐收藏').fontSize('12fp').fontColor('#999999').margin({right: '4vp'})
              Image($r('app.media.discovery_like')).width('15vp').height('15vp')
            }
          }
          .justifyContent(FlexAlign.SpaceBetween)
          .width('100%')
          .height('54vp')
          .padding({left: '10vp', right: '10vp'})

          ForEach(this.songList, (item: any) =>  {
            this.songItem(item)
          }, (item: any, index?: number) => index + JSON.stringify(item))

        }.width('100%')
      }
      .scrollable(ScrollDirection.Vertical)  // 滚动方向纵向
      .edgeEffect(EdgeEffect.None)
      // .backgroundColor('#889746')
    }.height('100%').padding({bottom: '52vp'})
  }
}